/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Plantp1": {
		"en": " Plant performance",
		"de": " Anlagenleistung",
		"ru": " Производительность завода",
		"pt": " Desempenho da planta",
		"nl": " Plant prestaties",
		"fr": " Performances de l'usine",
		"it": " Performance dell'impianto",
		"es": " Rendimiento de la planta",
		"pl": " Wydajność roślin",
		"zh-cn": " 工厂绩效"
	},
    "Plantp2": {
		"en": " Plant performance",
		"de": " Anlagenleistung",
		"ru": " Производительность завода",
		"pt": " Desempenho da planta",
		"nl": " Plant prestaties",
		"fr": " Performances de l'usine",
		"it": " Performance dell'impianto",
		"es": " Rendimiento de la planta",
		"pl": " Wydajność roślin",
		"zh-cn": " 工厂绩效"
	},
    "Plantp3": {
		"en": " Plant performance",
		"de": " Anlagenleistung",
		"ru": " Производительность завода",
		"pt": " Desempenho da planta",
		"nl": " Plant prestaties",
		"fr": " Performances de l'usine",
		"it": " Performance dell'impianto",
		"es": " Rendimiento de la planta",
		"pl": " Wydajność roślin",
		"zh-cn": " 工厂绩效"
	},
    "Plantp4": {
		"en": " Plant performance",
		"de": " Anlagenleistung",
		"ru": " Производительность завода",
		"pt": " Desempenho da planta",
		"nl": " Plant prestaties",
		"fr": " Performances de l'usine",
		"it": " Performance dell'impianto",
		"es": " Rendimiento de la planta",
		"pl": " Wydajność roślin",
		"zh-cn": " 工厂绩效"
	},
    "Plantp5": {
		"en": " Plant performance",
		"de": " Anlagenleistung",
		"ru": " Производительность завода",
		"pt": " Desempenho da planta",
		"nl": " Plant prestaties",
		"fr": " Performances de l'usine",
		"it": " Performance dell'impianto",
		"es": " Rendimiento de la planta",
		"pl": " Wydajność roślin",
		"zh-cn": " 工厂绩效"
	},
	"pvname1":{
		"en": "pv plant name",
		"de": "PV Anlagenname",
		"ru": "pv название завода",
		"pt": "nome da planta pv",
		"nl": "pv plant naam",
		"fr": "nom de la plante pv",
		"it": "nome dell'impianto fotovoltaico",
		"es": "nombre de la planta pv",
		"pl": "nazwa rośliny pv",
		"zh-cn": "光伏工厂名称"			
	},
	"pvname2":{
		"en": "pv plant name",
		"de": "PV Anlagenname",
		"ru": "pv название завода",
		"pt": "nome da planta pv",
		"nl": "pv plant naam",
		"fr": "nom de la plante pv",
		"it": "nome dell'impianto fotovoltaico",
		"es": "nombre de la planta pv",
		"pl": "nazwa rośliny pv",
		"zh-cn": "光伏工厂名称"			
	},
	"pvname3":{
		"en": "pv plant name",
		"de": "PV Anlagenname",
		"ru": "pv название завода",
		"pt": "nome da planta pv",
		"nl": "pv plant naam",
		"fr": "nom de la plante pv",
		"it": "nome dell'impianto fotovoltaico",
		"es": "nombre de la planta pv",
		"pl": "nazwa rośliny pv",
		"zh-cn": "光伏工厂名称"			
	},
	"pvname4":{
		"en": "pv plant name",
		"de": "PV Anlagenname",
		"ru": "pv название завода",
		"pt": "nome da planta pv",
		"nl": "pv plant naam",
		"fr": "nom de la plante pv",
		"it": "nome dell'impianto fotovoltaico",
		"es": "nombre de la planta pv",
		"pl": "nazwa rośliny pv",
		"zh-cn": "光伏工厂名称"			
	},
	"pvname5":{
		"en": "pv plant name",
		"de": "PV Anlagenname",
		"ru": "pv название завода",
		"pt": "nome da planta pv",
		"nl": "pv plant naam",
		"fr": "nom de la plante pv",
		"it": "nome dell'impianto fotovoltaico",
		"es": "nombre de la planta pv",
		"pl": "nazwa rośliny pv",
		"zh-cn": "光伏工厂名称"			
	},	
    "tilt1": {
		"en": "tilt",
		"de": "Neigung",
		"ru": "наклон",
		"pt": "inclinar",
		"nl": "kantelen",
		"fr": "inclinaison",
		"it": "inclinazione",
		"es": "inclinación",
		"pl": "przechylenie",
		"zh-cn": "倾斜"
    },
    "tilt2": {
		"en": "tilt",
		"de": "Neigung",
		"ru": "наклон",
		"pt": "inclinar",
		"nl": "kantelen",
		"fr": "inclinaison",
		"it": "inclinazione",
		"es": "inclinación",
		"pl": "przechylenie",
		"zh-cn": "倾斜"
    },
    "tilt3": {
		"en": "tilt",
		"de": "Neigung",
		"ru": "наклон",
		"pt": "inclinar",
		"nl": "kantelen",
		"fr": "inclinaison",
		"it": "inclinazione",
		"es": "inclinación",
		"pl": "przechylenie",
		"zh-cn": "倾斜"
    },
    "tilt4": {
		"en": "tilt",
		"de": "Neigung",
		"ru": "наклон",
		"pt": "inclinar",
		"nl": "kantelen",
		"fr": "inclinaison",
		"it": "inclinazione",
		"es": "inclinación",
		"pl": "przechylenie",
		"zh-cn": "倾斜"
    },
    "tilt5": {
		"en": "tilt",
		"de": "Neigung",
		"ru": "наклон",
		"pt": "inclinar",
		"nl": "kantelen",
		"fr": "inclinaison",
		"it": "inclinazione",
		"es": "inclinación",
		"pl": "przechylenie",
		"zh-cn": "倾斜"
    },		
	"Azimuth1": {
		"en": "Azimuth",
		"de": "Azimut",
		"ru": "Азимут",
		"pt": "Azimute",
		"nl": "Azimuth",
		"fr": "Azimut",
		"it": "Azimut",
		"es": "Azimut",
		"pl": "Azymut",
		"zh-cn": "方位角"
    }, 
	"Azimuth2": {
		"en": "Azimuth",
		"de": "Azimut",
		"ru": "Азимут",
		"pt": "Azimute",
		"nl": "Azimuth",
		"fr": "Azimut",
		"it": "Azimut",
		"es": "Azimut",
		"pl": "Azymut",
		"zh-cn": "方位角"
    }, 	
	"Azimuth3": {
		"en": "Azimuth",
		"de": "Azimut",
		"ru": "Азимут",
		"pt": "Azimute",
		"nl": "Azimuth",
		"fr": "Azimut",
		"it": "Azimut",
		"es": "Azimut",
		"pl": "Azymut",
		"zh-cn": "方位角"
    }, 	
	"Azimuth4": {
		"en": "Azimuth",
		"de": "Azimut",
		"ru": "Азимут",
		"pt": "Azimute",
		"nl": "Azimuth",
		"fr": "Azimut",
		"it": "Azimut",
		"es": "Azimut",
		"pl": "Azymut",
		"zh-cn": "方位角"
    },
	"Azimuth5": {
		"en": "Azimuth",
		"de": "Azimut",
		"ru": "Азимут",
		"pt": "Azimute",
		"nl": "Azimuth",
		"fr": "Azimut",
		"it": "Azimut",
		"es": "Azimut",
		"pl": "Azymut",
		"zh-cn": "方位角"
    },
	"legende1": {
		"en": "legende",
		"de": "Legende",
		"ru": "legende",
		"pt": "legende",
		"nl": "legende",
		"fr": "légende",
		"it": "legenda",
		"es": "legende",
		"pl": "legenda",
		"zh-cn": "传奇"
	},
	"legende2": {
		"en": "legende",
		"de": "Legende",
		"ru": "legende",
		"pt": "legende",
		"nl": "legende",
		"fr": "légende",
		"it": "legenda",
		"es": "legende",
		"pl": "legenda",
		"zh-cn": "传奇"
	},
	"legende3": {
		"en": "legende",
		"de": "Legende",
		"ru": "legende",
		"pt": "legende",
		"nl": "legende",
		"fr": "légende",
		"it": "legenda",
		"es": "legende",
		"pl": "legenda",
		"zh-cn": "传奇"
	},	
    "legende4": {
		"en": "legende",
		"de": "Legende",
		"ru": "legende",
		"pt": "legende",
		"nl": "legende",
		"fr": "légende",
		"it": "legenda",
		"es": "legende",
		"pl": "legenda",
		"zh-cn": "传奇"
	},	
    "legende5": {
		"en": "legende",
		"de": "Legende",
		"ru": "legende",
		"pt": "legende",
		"nl": "legende",
		"fr": "légende",
		"it": "legenda",
		"es": "legende",
		"pl": "legenda",
		"zh-cn": "传奇"
	},	
	"graph color1": {
		"en": "graph color",
		"de": "Diagrammfarbe",
		"ru": "цвет графика",
		"pt": "cor do gráfico",
		"nl": "grafiek kleur",
		"fr": "couleur du graphique",
		"it": "colore del grafico",
		"es": "color del gráfico",
		"pl": "kolor wykresu",
		"zh-cn": "图形颜色"
	},
	"graph color2": {
		"en": "graph color",
		"de": "Diagrammfarbe",
		"ru": "цвет графика",
		"pt": "cor do gráfico",
		"nl": "grafiek kleur",
		"fr": "couleur du graphique",
		"it": "colore del grafico",
		"es": "color del gráfico",
		"pl": "kolor wykresu",
		"zh-cn": "图形颜色"
	},
    "graph color3": {
		"en": "graph color",
		"de": "Diagrammfarbe",
		"ru": "цвет графика",
		"pt": "cor do gráfico",
		"nl": "grafiek kleur",
		"fr": "couleur du graphique",
		"it": "colore del grafico",
		"es": "color del gráfico",
		"pl": "kolor wykresu",
		"zh-cn": "图形颜色"
	},
    "graph color4": {
		"en": "graph color",
		"de": "Diagrammfarbe",
		"ru": "цвет графика",
		"pt": "cor do gráfico",
		"nl": "grafiek kleur",
		"fr": "couleur du graphique",
		"it": "colore del grafico",
		"es": "color del gráfico",
		"pl": "kolor wykresu",
		"zh-cn": "图形颜色"
	},
    "graph color5": {
		"en": "graph color",
		"de": "Diagrammfarbe",
		"ru": "цвет графика",
		"pt": "cor do gráfico",
		"nl": "grafiek kleur",
		"fr": "couleur du graphique",
		"it": "colore del grafico",
		"es": "color del gráfico",
		"pl": "kolor wykresu",
		"zh-cn": "图形颜色"
	},
	"datalabel Color1": {
		"en": "datalabel Color",
		"de": "Datenetikett Farbe",
		"ru": "цвет метки данных",
		"pt": "datalabel Color",
		"nl": "datalabel Kleur",
		"fr": "Couleur de l'étiquette de données",
		"it": "etichetta dati Colore",
		"es": "color de la etiqueta de datos",
		"pl": "kolor etykiety danych",
		"zh-cn": "数据标签颜色"
	},
    "datalabel Color2": {
		"en": "datalabel Color",
		"de": "Datenetikett Farbe",
		"ru": "цвет метки данных",
		"pt": "datalabel Color",
		"nl": "datalabel Kleur",
		"fr": "Couleur de l'étiquette de données",
		"it": "etichetta dati Colore",
		"es": "color de la etiqueta de datos",
		"pl": "kolor etykiety danych",
		"zh-cn": "数据标签颜色"
	},
    "datalabel Color3": {
		"en": "datalabel Color",
		"de": "Datenetikett Farbe",
		"ru": "цвет метки данных",
		"pt": "datalabel Color",
		"nl": "datalabel Kleur",
		"fr": "Couleur de l'étiquette de données",
		"it": "etichetta dati Colore",
		"es": "color de la etiqueta de datos",
		"pl": "kolor etykiety danych",
		"zh-cn": "数据标签颜色"
	},
    "datalabel Color4": {
		"en": "datalabel Color",
		"de": "Datenetikett Farbe",
		"ru": "цвет метки данных",
		"pt": "datalabel Color",
		"nl": "datalabel Kleur",
		"fr": "Couleur de l'étiquette de données",
		"it": "etichetta dati Colore",
		"es": "color de la etiqueta de datos",
		"pl": "kolor etykiety danych",
		"zh-cn": "数据标签颜色"
	},
   "datalabel Color5": {
		"en": "datalabel Color",
		"de": "Datenetikett Farbe",
		"ru": "цвет метки данных",
		"pt": "datalabel Color",
		"nl": "datalabel Kleur",
		"fr": "Couleur de l'étiquette de données",
		"it": "etichetta dati Colore",
		"es": "color de la etiqueta de datos",
		"pl": "kolor etykiety danych",
		"zh-cn": "数据标签颜色"
	},
	"datalabel_rotation1": {
		"en": "datalabel rotation",
		"de": "Datalabel-Rotation",
		"ru": "вращение метки данных",
		"pt": "rotação do datalabel",
		"nl": "datalabel rotatie",
		"fr": "rotation des étiquettes de données",
		"it": "rotazione etichetta dati",
		"es": "rotación de etiquetas de datos",
		"pl": "rotacja etykiet danych",
		"zh-cn": "数据标签轮换"
	},	
	"axis y step1": {
		"en": "axis y step",
		"de": "Achse y Schritt",
		"ru": "шаг оси y",
		"pt": "eixo y passo",
		"nl": "as y stap",
		"fr": "pas de l'axe y",
		"it": "asse y passo",
		"es": "paso del eje y",
		"pl": "oś y krok",
		"zh-cn": "y轴步骤"
	},
	"Link from Solar Forecast": {	
		"en": "Link from Solar Forecast",
		"de": "Link von Solar Forecast",
		"ru": "Ссылка из Solar Forecast",
		"pt": "Link da previsão solar",
		"nl": "Link van Solar Forecast",
		"fr": "Lien depuis les prévisions solaires",
		"it": "Collegamento da Solar Forecast",
		"es": "Enlace del pronóstico solar",
		"pl": "Link z prognozy słonecznej",
		"zh-cn": "太阳能预报的链接"
    },	
	"APIK": {
		"en": "API-key",
		"de": "API-Schlüssel",
		"ru": "API-ключ",
		"pt": "Chave API",
		"nl": "API sleutel",
		"fr": "Clé API",
		"it": "Chiave API",
		"es": "Clave API",
		"pl": "Klucz API",
		"zh-cn": "API密钥"
    },
	"https://api.forecast.solar": {
		"en": "https://api.forecast.solar",
		"de": "https://api.forecast.solar",
		"ru": "https://api.forecast.solar",
		"pt": "https://api.forecast.solar",
		"nl": "https://api.forecast.solar",
		"fr": "https://api.forecast.solar",
		"it": "https://api.forecast.solar",
		"es": "https://api.forecast.solar",
		"pl": "https://api.forecast.solar",
		"zh-cn": "https://api.forecast.solar"
	},
    "longitude": {
		"en": "longitude",
		"de": "Längengrad",
		"ru": "долгота",
		"pt": "longitude",
		"nl": "Lengtegraad",
		"fr": "longitude",
		"it": "longitudine",
		"es": "longitud",
		"pl": "długość geograficzna",
		"zh-cn": "经度"
    },
    "latitude": {
		"en": "latitude",
		"de": "Breite",
		"ru": "широта",
		"pt": "latitude",
		"nl": "breedtegraad",
		"fr": "latitude",
		"it": "latitudine",
		"es": "latitud",
		"pl": "szerokość",
		"zh-cn": "纬度"
    }
};






